server:
  port: 9000

spring:
  profiles:
    active: "qa"
  application:
    name: "cards"

  config:
    import: optional:configserver:http://configserver:8071/

  cloud:
    config:
      uri: http://configserver:8071
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000

  datasource:
    url: jdbc:h2:mem:cardsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/

info:
  app:
    name: "cards"
    description: "Cards MicroService"

logging:
  level:
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: DEBUG
